version: '3.5'

services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_DATABASE: development
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
      TZ: Asia/Tokyo
    ports:
      - "33061:3306"
    volumes:
      - db-data:/var/lib/mysql
  app:
    platform: linux/amd64
    build:
      context: .
    command: sh -c "rm -f tmp/pids/* && bundle && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      TZ: Asia/Tokyo
      ENV_NAME: development
      DB_HOST: db
      DB_NAME: development
      DB_USERNAME: root
      DB_PASSWORD: password
    volumes:
      - ./:/app
    ports:
      - "1700:1700"
    depends_on:
      - db
    links:
      - db
    tty: true
    stdin_open: true
volumes:
  db-data:
    driver: local
